#ifndef SMARTRF_SETTINGS_PREDEFINED
#define SMARTRF_SETTINGS_PREDEFINED


//*********************************************************************************
// Generated by SmartRF Studio version 2.6.0 (build #81)
// Tested for SimpleLink SDK version: CC13x0 SDK 1.0.xx
// Device: CC1310 Rev. 2.1
//
//*********************************************************************************


#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_hs_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_hs_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)

#include <ti/drivers/rf/RF.h>

/* TX Power dBm lookup table - values from SmartRF Studio */
typedef struct
{
    int8_t dbm;
    uint16_t txPower; /* Value for the PROP_DIV_RADIO_SETUP.txPower field */
} rfPowerConfig_t;

extern const uint8_t rfPowerTableSize;
extern const rfPowerConfig_t rfPowerTable[];

/* RF Core API commands */
/* RF command pointers for easylink */
extern RF_Mode *RF_pProp_fsk;
extern RF_Mode *RF_pProp_lrm;
extern RF_Mode *RF_pProp_ook;
extern RF_Mode *RF_pProp_hsm;
extern RF_Mode *RF_pProp_sl_lr;
extern RF_Mode *RF_pProp_2_4G_fsk;

extern rfc_CMD_PROP_RADIO_DIV_SETUP_t *RF_pCmdPropRadioDivSetup_fsk;
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t *RF_pCmdPropRadioDivSetup_lrm;
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t *RF_pCmdPropRadioDivSetup_ook;
extern rfc_CMD_RADIO_SETUP_t          *RF_pCmdRadioSetup_hsm;
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t *RF_pCmdPropRadioDivSetup_sl_lr;
extern rfc_CMD_PROP_RADIO_SETUP_t *RF_pCmdPropRadioSetup_2_4G_fsk;

extern rfc_CMD_HS_TX_t *RF_pCmdTxHS;
extern rfc_CMD_HS_RX_t *RF_pCmdRxHS;
extern rfc_CMD_FS_t *RF_pCmdFs_preDef;
extern rfc_CMD_PROP_TX_t *RF_pCmdPropTx_preDef;
extern rfc_CMD_PROP_RX_ADV_t *RF_pCmdPropRxAdv_preDef;

extern uint32_t pOverrides_fsk[];
extern uint32_t pOverrides_lrm[];
extern uint32_t pOverrides_sl_lr[];

#endif // SMARTRF_SETTINGS_PREDEFINED
